In [137]:
%run -m ipy_startup

In [138]:
from sklearn.linear_model import Ridge

In [139]:
n = 10
p = 3
d = np.random.randn(n, p)
d = np.hstack((np.ones((10, 1)), d))
dh = np.mean(d, axis=0)
dh = np.repeat(np.reshape(dh, (-1, 1)), n, axis=1).T
b = np.array([1, 1, .5, 0])
y = np.dot(d, b)
d, y

(array([[ 1.        ,  0.98826671,  0.69079169,  1.54392859],
        [ 1.        , -0.56390941, -1.71830628,  0.33467423],
        [ 1.        ,  0.53257642,  0.2566109 , -0.05528603],
        [ 1.        ,  0.15053761,  0.70168193,  0.46105576],
        [ 1.        ,  0.36128768,  0.18848588,  0.17610384],
        [ 1.        , -1.76490603, -0.21587501, -0.85888912],
        [ 1.        ,  0.332849  , -2.03248529,  1.53781048],
        [ 1.        , -1.53250631, -0.43814661,  0.8894395 ],
        [ 1.        ,  0.43172347,  0.47227341,  0.05562302],
        [ 1.        , -0.41551664,  0.14767624,  0.32522431]]),
 array([ 2.33366255, -0.42306255,  1.66088187,  1.50137857,  1.45553062,
        -0.87284354,  0.31660636, -0.75157961,  1.66786017,  0.65832148]))

In [140]:
dh

array([[ 1.        , -0.14795975, -0.19472931,  0.44096846],
       [ 1.        , -0.14795975, -0.19472931,  0.44096846],
       [ 1.        , -0.14795975, -0.19472931,  0.44096846],
       [ 1.        , -0.14795975, -0.19472931,  0.44096846],
       [ 1.        , -0.14795975, -0.19472931,  0.44096846],
       [ 1.        , -0.14795975, -0.19472931,  0.44096846],
       [ 1.        , -0.14795975, -0.19472931,  0.44096846],
       [ 1.        , -0.14795975, -0.19472931,  0.44096846],
       [ 1.        , -0.14795975, -0.19472931,  0.44096846],
       [ 1.        , -0.14795975, -0.19472931,  0.44096846]])

In [134]:
est = Ridge(fit_intercept=False, normalize=False, alpha=1.)
est.fit(d, y)
est.coef_

array([ 0.71072287,  0.85005135,  0.31575083, -0.13746824])

In [135]:
est = Ridge(fit_intercept=False, normalize=False, alpha=1.)
X = d - dh
X[:,0] = 1
est.fit(X, y)
est.coef_

array([ 0.1789955 ,  0.90022607,  0.39836341, -0.0748735 ])

In [101]:
def get_ridge_coefs(d, alpha):
    return np.dot(np.dot(np.linalg.inv(np.dot(d.T, d) + alpha * np.eye(d.shape[1])), d.T), y)

In [103]:
get_ridge_coefs(d, 1)

array([ 0.96187598,  0.82942005,  0.47634786, -0.14917297])

In [104]:
get_ridge_coefs(dh, 1)

array([ 1.05806947,  0.17256724,  0.32193708,  0.16346318])

In [106]:
d

array([[ 1.        ,  0.74463874, -0.45495711, -0.3687891 ],
       [ 1.        , -0.54488594,  0.78065966,  1.23190545],
       [ 1.        , -0.38517494,  0.28660867,  0.54483023],
       [ 1.        ,  1.18581434, -0.61771719,  0.12485629],
       [ 1.        , -1.37672752,  0.53015711,  1.41600915],
       [ 1.        , -2.34469545, -1.03485277,  2.26347858],
       [ 1.        ,  0.38331348,  1.25953654, -0.6647481 ],
       [ 1.        ,  0.66202557,  2.42410343, -0.46477879],
       [ 1.        ,  1.42115462,  0.58011974, -0.52286189],
       [ 1.        ,  1.88550036, -0.71097427, -2.01498269]])

In [98]:
est2 = Ridge(fit_intercept=True, normalize=True)
est2.fit(d, y)
est2.coef_

array([ 0.        ,  0.36757365,  0.25933202, -0.32571714])

In [28]:
from sklearn.preprocessing import StandardScaler
est2 = Ridge(fit_intercept=False, normalize=False)
scaler = StandardScaler(with_std=False)
#pd.DataFrame(scaler.fit_transform(d)).describe()
est2.fit(scaler.fit_transform(d), y)
est2.coef_

array([ 0.        ,  0.86303043,  0.36344384, -0.01848619])

In [53]:
scaler.fit_transform(d)

array([[ 0.        , -0.30905463,  0.53920769, -0.87298364],
       [ 0.        , -0.67817603, -0.78057886,  0.60846845],
       [ 0.        , -1.38004272,  0.40738172, -0.04221903],
       [ 0.        ,  0.16388985, -0.12091719,  1.41985942],
       [ 0.        , -0.33755971,  0.89211952,  0.16006641],
       [ 0.        ,  0.02808699,  0.23436833,  0.3007047 ],
       [ 0.        ,  2.07993279, -0.10222746,  0.03497708],
       [ 0.        , -0.16926617, -1.03609712,  0.33454895],
       [ 0.        ,  0.01207526,  0.48898253,  0.18244235],
       [ 0.        ,  0.59011438, -0.52223916, -2.12586469]])

In [25]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [55]:
np.array([[1,2], [3, 4], [5, 6]]).T

array([[1, 3, 5],
       [2, 4, 6]])

In [54]:
np.dot(np.array([[1,2], [3, 4], [5, 6]]).T, np.array([[1,2], [3, 4], [5, 6]]))

array([[35, 44],
       [44, 56]])

In [66]:
x

array([[ 1.        , -0.18688326,  1.17734072, -0.59992053],
       [ 1.        , -0.55600466, -0.14244583,  0.88153156],
       [ 1.        , -1.25787135,  1.04551476,  0.23084408],
       [ 1.        ,  0.28606122,  0.51721584,  1.69292253],
       [ 1.        , -0.21538833,  1.53025256,  0.43312952],
       [ 1.        ,  0.15025836,  0.87250136,  0.57376781],
       [ 1.        ,  2.20210416,  0.53590557,  0.30804019],
       [ 1.        , -0.04709479, -0.39796409,  0.60761206],
       [ 1.        ,  0.13424664,  1.12711556,  0.45550546],
       [ 1.        ,  0.71228576,  0.11589387, -1.85280158]])

In [67]:
xh

array([[ 1.        ,  0.12217138,  0.63813303,  0.27306311],
       [ 1.        ,  0.12217138,  0.63813303,  0.27306311],
       [ 1.        ,  0.12217138,  0.63813303,  0.27306311],
       [ 1.        ,  0.12217138,  0.63813303,  0.27306311],
       [ 1.        ,  0.12217138,  0.63813303,  0.27306311],
       [ 1.        ,  0.12217138,  0.63813303,  0.27306311],
       [ 1.        ,  0.12217138,  0.63813303,  0.27306311],
       [ 1.        ,  0.12217138,  0.63813303,  0.27306311],
       [ 1.        ,  0.12217138,  0.63813303,  0.27306311],
       [ 1.        ,  0.12217138,  0.63813303,  0.27306311]])

In [77]:
def get_coefs(b0, x, xh, y, n, p, alpha):
    m0 = x - xh
    m1 = np.linalg.inv(np.dot(x.T, x) + alpha * np.eye(p))
    
    m2 = np.dot(m1, np.dot(m0.T, m0) + alpha * np.eye(p))
    
    print(m1.shape, xh.shape, y.shape)
    m3 = b0 - np.dot(m1, np.dot(xh.T, y))
    
    return np.dot(np.linalg.inv(m2), m3)

In [78]:
x = d
n = x.shape[0]
p = x.shape[1]
b0 = est2.coef_
xh = np.mean(x, axis=0)
xh = np.repeat(np.reshape(xh, (-1, 1)), n, axis=1).T
alpha = 1.

In [79]:
get_coefs(b0, x, xh, y, n, p, alpha)

(4, 4) (10, 4) (10,)


array([ 18.91077351,   1.52246149,   3.16420482,   0.6659422 ])